name: Build & upload artifact on published release

on:
  release:
    types: [published]

  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string
  
permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  build-package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ 'amd64' ]
        krakend-builder-image: [ 'builder:2.2.1', 'builder:2.2', 'builder:2', 'builder-ee:2.2.0', 'builder-ee:2.2', 'builder-ee:2' ]
    steps:
      - uses: actions/checkout@v3

      - name: Set RELEASE_VERSION
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Build plugin
        run: |
          make build ARCH=${{ matrix.arch }} KRAKEND_BUILDER_IMAGE=${{ matrix.krakend-builder-image }} RELEASE_VERSION=${{ env.RELEASE_VERSION }}

      - name: Sanitise KrakenD builder image name
        run: |
          KRAKEND_BUILDER_IMAGE=${{ matrix.krakend-builder-image }}
          KRAKEND_BUILDER_IMAGE=${KRAKEND_BUILDER_IMAGE/:/-}
          echo KRAKEND_BUILDER_IMAGE=${KRAKEND_BUILDER_IMAGE} >> $GITHUB_ENV

      - name: Upload plugin .so file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: firetail-krakend-plugin-${{ matrix.arch }}-${{ env.KRAKEND_BUILDER_IMAGE }}-${{ env.RELEASE_VERSION }}
          path: firetail-krakend-plugin-${{ matrix.arch }}-${{ env.KRAKEND_BUILDER_IMAGE }}-${{ env.RELEASE_VERSION }}.so

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload release binary
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_name: firetail-krakend-plugin-${{ matrix.arch }}-${{ env.KRAKEND_BUILDER_IMAGE }}-${{ env.RELEASE_VERSION }}.so
          asset_path: firetail-krakend-plugin-${{ matrix.arch }}-${{ env.KRAKEND_BUILDER_IMAGE }}-${{ env.RELEASE_VERSION }}.so
          asset_content_type: application/x-sharedlib
